version: "3"
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: genshin_feedback
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_TCP_PORT: 3307
    volumes:
      - ${PWD}/mysql/db/:/var/lib/mysql
    ports:
      - "3307:3307"

  web:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3001:3001"
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - database
